# Generated by Django 5.2.4 on 2025-07-07 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_p9form_taxrecord_taxzip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
